/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sanxiang_project_JniUtils */

#ifndef _Included_com_sanxiang_project_JniUtils
#define _Included_com_sanxiang_project_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sanxiang_project_JniUtils
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sanxiang_project_JniUtils_getStringFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
